name = "RxEnvironmentsZoo"
uuid = "adb3f080-5af9-40cb-b3ca-0db92be4ebef"
authors = ["Wouter Nuijten <wouternuijten@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
RxEnvironments = "5ea003d0-0c30-4e5c-84d5-cc22d8d83890"

[compat]
DifferentialEquations = "7"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
